runtime: nodejs16

env_variables:
  JWT_SECRET: "jghguhguish993"
  MONGO_URI: "mongodb+srv://budgety-nestdb:budgetyDB@budgety-nestdb.1zmm4.mongodb.net/BudgetyNestApp?retryWrites=true&w=majority"
  PORT: 8080

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
