runtime: nodejs16

env_variables:
  JWT_SECRET: "jghguhguish993"
  MONGO_URI: "mongodb+srv://JmartinezBudgety:budgetypassword1@cluster0.qfer0mw.mongodb.net/Budgety?retryWrites=true&w=majority"
  NODE_ENV: "prod"
  ORIGIN_URL: "https://budgety-front-end.uc.r.appspot.com/"
  PORT: 8080

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
